#!/usr/bin/bash

#                                      Copyright 2025 WebPros International, LLC
#                                                           All rights reserved.
# copyright@cpanel.net                                         http://cpanel.net
# This code is subject to the cPanel license. Unauthorized copying is prohibited.

# RE-1179 / RE-1244
if [[ ! -f "/etc/scl/prefixes/ea-php80" ]]
then
	echo -e "\nFile does not exist at /etc/scl/prefixes/ea-php80; installing ea-php80 via scripts/installpkg"
	/usr/local/cpanel/scripts/installpkg ea-php80
else
	echo -e "\nFile already exists at /etc/scl/prefixes/ea-php80; skipping install of ea-php80."
fi

# RE-1416 / RE-1461
echo -e "\nInstalling ea-nginx via scripts/installpkg"
/usr/local/cpanel/scripts/installpkg ea-nginx

# RE-1568
if [[ -f /etc/redhat-release ]] && grep -q "^CentOS.*release 7" /etc/redhat-release; then
    sed -i 's/CPANEL=.*/CPANEL=11.110/' /etc/cpupdate.conf
fi

# RE-1573
echo "Creating 3 accounts"
for DOMAIN in withfpm nofpm inherit; do /usr/local/cpanel/bin/whmapi1 createacct username=$DOMAIN domain=$DOMAIN.tld; done

echo "Clearing the task queue"
/usr/local/cpanel/bin/servers_queue run

echo "Setting 'withfpm' account to ea-php81 with php-fpm enabled"
/usr/local/cpanel/bin/whmapi1 php_set_vhost_versions version=ea-php81 vhost=withfpm.tld php_fpm=1

echo "Setting 'nofpm' account to ea-php82 with php-fpm disabled"
/usr/local/cpanel/bin/whmapi1 php_set_vhost_versions version=ea-php82 vhost=nofpm.tld php_fpm=0

echo "Setting 'inherit' account to inherit the default PHP version"
/usr/local/cpanel/bin/whmapi1 php_set_vhost_versions version=inherit vhost=inherit.tld

echo "Clearing the task queue"
/usr/local/cpanel/bin/servers_queue run

exit 0;
