# action.yml
name: 'Build & Prep'
description: 'Build Docker Instance with Terraform'
outputs:
  terraform: # id of output
    description: 'Version of Terraform verifying it is installed'
runs:
  using: 'docker'
  image: 'Dockerfile'

