#!/usr/local/cpanel/3rdparty/bin/perl

use constant ELEVATE_LOG_PATH => '/var/log/elevate-cpanel.log';

use File::Tail;
use POSIX;

my $RETVAL = 1;

# Verify REBOOT_STRING isn't already in the log before we go into tail mode.  The logodump here is sgnificantly faster than File::Tail.
# Jump if it's found.

exit 1 if !length( $ENV{REBOOT_STRING} );

open( my $elevate_log_fh, '<', ELEVATE_LOG_PATH ) or die "## [ERROR][reboot_watch]: Unable to open ELEVATE_LOG_PATH: $!\n";

while ( my $line = readline $elevate_log_fh ) {
    if ( index( $line, $ENV{REBOOT_STRING} ) >= 0 ) {
        _success_message();
        close $elevate_log;
        exit 0;
    }
}

close $elevate_log_fh;

while ( $RETVAL != 0 ) {
    _check_elevate_log_for_REBOOT_STRING( ELEVATE_LOG_PATH, $ENV{REBOOT_STRING} );
    exit 0;
}

sub _check_elevate_log_for_REBOOT_STRING {
    my ( $filepath, $REBOOT_STRING, $RETRIES ) = @_;

    $file = File::Tail->new( name => $filepath, maxinterval => 1, adjustafter => 7, interval => 1 );
    while ( defined( $line = $file->read ) ) {
        if ( index( $line, $ENV{REBOOT_STRING} ) >= 0 ) {
            _success_message();
        }
    }
}

sub _success_message {
    my $time = POSIX::strftime( "%Y-%m-%d %H:%M:%S", localtime );
    print "## [$time] [INFO]: SUCCESS: Reboot REBOOT_STRING ( $ENV{REBOOT_STRING} ) found in /var/log/elevate-cpanel.log  ##\n";
    exit 0;
}

exit 0;
