#!/usr/bin/env perl

use POSIX;

my $HOST    = $ARGV[0];
my $PORT    = $ARGV[1] // 22;
my $RETVAL  = 1;
my $RETRIES = 0;
my $RETRY   = $ARGV[2] // 1800;    # Bumping this to 30 minutes per cloudlinux Stage 4 averaging right at 15 mins ( up to 30 mins in slow times )

my $NC_PATH = '/usr/bin/nc';

# Check if netcat is installed
unless ( -x $NC_PATH ) {
    my $pkg_suggestion = "Please install netcat manually.";
    if ( -x "/sbin/apk" || -x "/bin/apk" ) {
        $pkg_suggestion = "Try: apk add netcat-openbsd";
    }
    elsif ( -x "/usr/bin/apt" || -x "/bin/apt" ) {
        $pkg_suggestion = "Try: apt update && apt install -y netcat";
    }
    elsif ( -x "/usr/bin/yum" || -x "/bin/yum" ) {
        $pkg_suggestion = "Try: yum install -y nc";
    }
    print STDERR "Please install netcat as it's missing and ssh_retry rquires it.  HINT: $pkg_suggestion.";
    exit 1;
}

if ( !defined $HOST ) {
    print STDERR "No Host was defined.  exiting.\n";
    exit 1;
}

# elevate-cpanel sleeps for 10 seconds before rebooting in CI mode to ensure
# that the CI has plenty of time to jump out of the server
# To avoid race conditions due to this, we sleep for 10 seconds before checking
# to see if the server has rebooted in order to ensure that the server has been
# rebooted before attempting to see if we can connect to it via ssh
sleep(10);

while ( $RETVAL != 0 ) {
    my $cmd    = qq{ $NC_PATH -z -w 1 $HOST $PORT };
    my $output = `$cmd`;
    my $time   = POSIX::strftime( "%Y-%m-%d %H:%M:%S", localtime );

    $RETVAL = $?;

    if ( $RETVAL == 0 ) {
        print "## [$time] [INFO] SUCCESS: Connected to SSH on $HOST ##\n";
        exit 0;
    }

    $RETRIES++;

    if ( $RETVAL != 0 ) {
        print "## [$time] [INFO]: Retrying SSH Connect: Attempt ${RETRIES} to SSH on Host $HOST...\n";
    }

    if ( $RETRIES >= $RETRY ) {
        print "## [$time] [ERROR]: ssh_retry.pl: MAX_RETRIES has been reached.\n";
        exit 1;
    }
    sleep 1;
}
