#!/usr/local/cpanel/3rdparty/bin/perl

use Cpanel::OS;

use strict;

my $STAGE          = $ARGV[0];
my $RELEASE_INFO   = Cpanel::OS::display_name();
my $CPANEL_VERSION = `cat /usr/local/cpanel/version`;

print "###################################\n";

sub main {
    my @arr = (
        [ 'Stage:', $STAGE ], [ 'OS Release:', $RELEASE_INFO ]
        ,                     [ 'cP Version:', $CPANEL_VERSION ]
    );

    for my $row (@arr) {
        format STDOUT =
@<<<<<<<<<<  @<<<<<<<<<<<<<<<<<<<<<
         @$row
.
        write;
    }

}

main();

print "###################################\n";
