#!perl

#                                      Copyright 2024 WebPros International, LLC
#                                                           All rights reserved.
# copyright@cpanel.net                                         http://cpanel.net
# This code is subject to the cPanel license. Unauthorized copying is prohibited.

##
## This file is listing extra dependencies not provided by the default cPanel stack
##

# test
on 'test' => sub {

    requires "Test::MockFile" => "0.032";

    # test coverage
    recommends "Test::Perl::Critic";
    recommends "Test::PerlTidy";
    recommends "Test::Pod";

    # fatpack
    recommends "Module::Want";
    recommends "Perl::Tidy";
};
