#!/bin/bash

#                                      Copyright 2024 WebPros International, LLC
#                                                           All rights reserved.
# copyright@cpanel.net                                         http://cpanel.net
# This code is subject to the cPanel license. Unauthorized copying is prohibited.

set -ex

ULC=/usr/local/cpanel
VERSION=11.110.0.17
REPO=$(pwd)

yum clean all

yum install -y \
    pcre2 \
    wget \
    xz

wget http://httpupdate.cpanel.net/cpanelsync/${VERSION}/install/common/cpanel.tar.xz.cpanelsync.nodecompress \
    -o wget.log \
    -O cpanel.tar.xz

ls -l cpanel.tar.xz
unxz cpanel.tar.xz

mkdir -p $ULC
mkdir -p /var/cpanel
mkdir -p $ULC/3rdparty/bin

tar xf cpanel.tar -C $ULC

pushd $ULC

export CPANEL_BASE_INSTALL=1

echo 'signature_validation=Off' >> /var/cpanel/cpanel.config

echo "# ............. setup symlinks"
ln -sf usr/local/cpanel/scripts /scripts
ln -sf /bin/true /usr/local/cpanel/bin/build_locale_databases
ln -sf /bin/true /usr/local/cpanel/scripts/restartsrv_tailwatchd
ln -sf /usr/local/cpanel/3rdparty/perl/536/bin/perl /usr/local/cpanel/3rdparty/bin/perl
ln -sf /opt/cpanel/perl5/536/bin/perltidy /usr/local/cpanel/3rdparty/perl/536/bin/perltidy

echo "CPANEL=${VERSION}" > /etc/cpupdate.conf

echo "# ............. /scripts/fix-cpanel-perl"
rm -f /usr/local/cpanel/3rdparty/perl/536/bin/perl
/scripts/fix-cpanel-perl ||:

echo "# ............. which perl"
which perl
ls -l /usr/local/cpanel/3rdparty/perl/536/bin/perl

echo "# ............. cpanm round 2"
perl bin/cpanm -n --cpanfile ${REPO}/t/cpanfile --installdeps .

echo "# ............. scripts/cpservice"
scripts/cpservice cpanel install ||:

echo "# ............. install fake tailwatchd service"
install ${REPO}/t/setup/tailwatchd.fake.service /etc/systemd/system/tailwatchd.service

echo "# ............. scripts/sysup"
/scripts/sysup ||:

echo "# ............ enable extra target"
/usr/local/cpanel/scripts/update_local_rpm_versions --edit target_settings.perl-enhanced installed ||:

echo "# ............. scripts/check_cpanel_pkgs"
/scripts/check_cpanel_pkgs --fix --no-digest ||:
