#!perl

#                                      Copyright 2024 WebPros International, LLC
#                                                           All rights reserved.
# copyright@cpanel.net                                         http://cpanel.net
# This code is subject to the cPanel license. Unauthorized copying is prohibited.

# test
on 'test' => sub {

    # test coverage
    recommends "Devel::Cover";
    recommends "Perl::Critic::Policy::TestingAndDebugging::ProhibitNoWarnings";
    recommends "Test::Perl::Critic";
    recommends "Test::PerlTidy";
    recommends "Test::Pod";

    # fatpack
    recommends "Module::Want";
    recommends "Perl::Tidy";
};
